### ISSUE TITLE
Use glow pager as viewer

### ISSUE THREAD

**Issue by etiennebonnafoux** [Linus-Mussmaecher/rucola#18]
**Describe the bug**
Hello

Issue #14  introduce second viewer and markdown viewer. I try to set it up with glow and its pager.
So in my config.toml I have
```toml
secondary_viewer = ["glow -p","%p"]
secondary_viewer_type = "Markdown"
```

But when I press `V` rucola crashes with the error ` Error: IO(Os { code: 2, kind: NotFound, message: "No such file or directory" })` 

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 
 - Used editor nvim
 - Used viewer glow -p

**Additional context**
If I don't use the pager, glow render the markdown in the terminal and jump back to rucola interface so I don't have time to see it.

Thanks a lot for your help.
