### ISSUE TITLE
Files in vault_path not indexed

### ISSUE THREAD

**Issue by jederik** [Linus-Mussmaecher/rucola#2]
Hello. I love the idea of Rucola and am very excited to try it but currently I can't due to the following issue:

I installed Rucola via Cargo on Ubuntu 23.10. However, when I specify a *directory* as the `vault_path` the files in the directory are not listed in the Select View. On the other hand, when I specify an individual *file* then this one file is listed but no others and trying to view it gives me a `Not a directory (os error 20)`.

Hope this helps.

**Comment by Linus-Mussmaecher** [comment]
Hi. Obvious "this doesn't happen on my machine". Some things to check:
 - Are you configuring the directory in the same format as in the [default config](https://github.com/Linus-Mussmaecher/rucola/blob/main/default-config/config.toml)?
 - Do you have read/write permission for this directory?
 - Are the files you want to show up actually markdown files, i.e. have the `.md` extension or similar? `.txt`-Files, for example, or files without a file extension, will not be recognized.
 - By default, rucola ignores hidden files, hidden folders and respects your `.gitignore` file. Does this cause a problem here?
 - Maybe try to pass an absolute path (like `/home/linus/MyNotes` instead of `~/MyNotes`) as a test?

If all of this does not help, what happens if you pass the directory as a positional argument like `rucola ~/MyNotes` or `rucola /home/linus/MyNotes` instead of using the config file?
Maybe that can help us track down the error.

The error if you pass a file seems acceptable by me - you are supposed to pass a directory.

**Comment by jederik** [comment]
Hey. Thanks for the quick reply.

I checked all of your points but none of them helped.

- This is my `config.toml`:

  ```toml
  file_types = ["markdown"]
  default_extension = "md"
  theme = "default_dark"
  stats_show = "Both"
  viewer = [
      "firefox",
      "%p",
  ]
  enable_html = true
  css = "default_dark"
  katex = true
  vault_path = "/home/jederik/notes"
  
  [math_replacements]
  '\field' = '\mathbb'
  '\liealg' = '\mathfrak'
  ```

- I definitely have all permissions on `/home/jederik/notes`
- all files are `.md` files
- there is no git repo or hidden files
- absolute path doesn't help
- running `rucola /home/jederik/notes` shows the same behavior
- when removing the `vault_path` entry from the config and creating a `~/MyNotes` folder with some MD files in it, there seems to be some indexing on startup but still nothing is shown in the list.

Definitely, pointing to a file doesn't make much sense but I thought it might give you a clue on what the problem is.
